name: CI for Mood Analyzer

on:
  push:
    paths:
      - "mood-analyzer/**"
  pull_request:
    paths:
      - "mood-analyzer/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        cd mood-analyzer
        pip install -r requirements.txt

    - name: Lint check
      run: |
        pip install flake8
        flake8 mood-analyzer/main.py --max-line-length=120

    - name: Build Docker image
      run: docker build -t mood-analyzer:latest ./mood-analyzer

    - name: Upload Artifact (optional)
      uses: actions/upload-artifact@v3
      with:
        name: mood-analyzer
        path: mood-analyzer/
