name: CI/CD for Mood Analyzer

on:
  push:
    branches: [ main ]
    paths:
      - "mood-analyzer/**"
  pull_request:
    paths:
      - "mood-analyzer/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mood-analyzer
          push: true
          tags: sreejith777/mood-analyzer:latest

      - name: (Optional) Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mood-analyzer
          path: mood-analyzer/

# To deploy to Minikube, you need a self-hosted runner with kubectl configured.
# Add a job here for deployment if you set up a self-hosted runner.
